// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

const supabaseUrl = "https://roxtaxlzzsecztwuings.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJveHRheGx6enNlY3p0d3VpbmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzgzMDAsImV4cCI6MjA2MTQxNDMwMH0.8SQBo4ewZPSzj3kE2rCinUMZxOmyB25yFpsXnMlPEOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);